# Generated by Django 4.1.7 on 2023-04-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
